### PR TITLE
Fix incorrect entity scheduler retring issue

### PR DESCRIPTION
**Pull request by MrHua269**

### CODE REVIEW

**Comment by Spottedleaf** [comment]
provide a reason why this change is to be made? why are we avoiding retiring the scheduler of players who have been in the world but are in the change state?

**Comment by MrHua269** [comment]
> provide a reason why this change is to be made? why are we avoiding retiring the scheduler of players who have been in the world but are in the change state?

It will cause a crash if the player in configuration state and doesn't reply the keepalive from the server for more than 30s.

Like this(offline mode):
C -> S handshake
C -> S loginstart
S -> C loginsuccess
C -> S login acknowledged

S -> C Keepalive 
C: Do nothing and keep this state  and connection active(send something except keepalive reply) for 30s
and the server will crash when kicked the player for timedout.

I checked the source code and I found this:
image
image
and the same method "onDisconnect" will be called again after kicking in the next tick because the connection is still in the connection list in the global region and when the global region call the method "handleDisconnection",it will call the method "onDisconnect" again and retry the scheduler,then the scheduler throw a exception and the server crashed.Like this:

image

I also tried it on folia 1.20.4 and it still happened

**Comment by Spottedleaf** [comment]
Please re-test with https://github.com/PaperMC/Folia/commit/e89a107ef0d4a6f009ad81a2bf329b312c5e6cea

Due to the issue I described earlier, the actual retire() call needs to be in the common listener to ensure that the scheduler is retired in all cases

**Comment by MrHua269** [comment]
It's alright now,Thanks!

**Pull request closed without merging**
