### PR TITLE
Update Paper

### PR DESCRIPTION
**Pull request by FunixG**
# Update Folia to last commit of Paper

Hello ! That's my first contribution for Folia. I really want to help that project, I alaways wanted to manage a Minecraft server with multi threading.

I hope that I am doing right ! I have managed the conflicts with the upstream Paper repo and tested by running a Minecraft server

### CODE REVIEW

**Comment by Euphillya** [comment]
I don't think it will be accepted, see this comment: https://github.com/PaperMC/Folia/pull/220#issuecomment-2104933723

**Comment by mmTvv** [comment]
Up! It would be great if folia updated the paper more often

**Comment by FunixG** [comment]
I am planning to use that branch on my production server next week ! I will keep you updated for issues I will find, my server do not have many players actually so I can test this

**Review by Runkang10 — COMMENTED** [review]
.

**Comment by ocelotpotpie** [comment]
Closing this, as Leaf has stated that we don't really accept PRs for updating Paper due to the nature of the complexity, and we'd rather not have people "bumping" PRs or Github issues.

**Pull request closed without merging**
